### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by scls19fr** [quackenbush/APC#11]
Hello,

instead of using `print` statements we should use a logging library (with default logging to stdout).
So it'd make this library easier to integrate.

Kind regards

**Comment by quackenbush** [comment]
Sure, you're welcome to send a pull request.

By the way, which APC model are you using this with?

**Comment by scls19fr** [comment]
Ok I will do... but we first need to tackle https://github.com/quackenbush/APC/issues/4 because some logging libraries uses a configuration file and we should see how it can be handle correctly in a package.

I still don't know if we should use standard Python logging module https://docs.python.org/3/library/logging.html or Logbook https://logbook.readthedocs.io/

To answer your question I own a APC Switched Rack PDU Power Distribution Unit AP7921

**Comment by scls19fr** [comment]
Closed in favor of https://github.com/scls19fr/APC/issues/2
