### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by scls19fr** [quackenbush/APC#2]
Hello,

it will be nice to have Python 3 support.

Kind regards

**Comment by quackenbush** [comment]
It should work with Python3 now

**Comment by scls19fr** [comment]
Python 3 version is still broken

```python
$ python --version
Python 3.6.1 :: Anaconda custom (x86_64)
$ python apc.py --password **** --off 2
Acquiring lock /tmp/apc.lock
Connecting to APC @ 192.168.1.2
Traceback (most recent call last):
  File "apc.py", line 258, in <module>
    main()
  File "apc.py", line 237, in main
    apc = APC(args)
  File "apc.py", line 44, in __init__
    self.connect()
  File "apc.py", line 92, in connect
    match = APC_VERSION_PATTERN.search(header)
TypeError: cannot use a string pattern on a bytes-like object
```

Could you reopen this issue?

I'm using Anaconda Python to be able to switch from a Python version (default 3.6 to an other one such as 2.7)
https://conda.io/docs/user-guide/tasks/manage-environments.html

**Comment by quackenbush** [comment]
Would you try locally changing the line to this:

    match = APC_VERSION_PATTERN.search(str(header))

**Comment by scls19fr** [comment]
I works fine both with Python 2 and Python 3
PR https://github.com/quackenbush/APC/pull/14 submitted
