### ISSUE TITLE
Move project ownership to a GitHub organization

### ISSUE THREAD

**Issue by scls19fr** [quackenbush/APC#21]
Hello

My last PRs haven't been merged despite they provide useful feature (package, better handling of several APC version using classes and inheritance, delayed power on, delayed power off, status of outlets...)
I'm also aware that you don't own APC anymore.
So I wonder if this project shouldn't be move to a GitHub organization `apc-python` or `apc-tools` for example
What is your opinion @quackenbush ?

Kind regards

**Comment by quackenbush** [comment]
Yes, some of your pull requests don't merge, and I don't want to maintain future versions, especially if the architecture is being changed.

Here is my recommendation:  I will change my Github repo README file to either point to your repo, or to a new repo if you want to create one.

**Comment by scls19fr** [comment]
PR have been merged in my fork version (master branch) https://github.com/scls19fr/APC
All PR and issue (except this one) in your repository have been closed.

**Comment by quackenbush** [comment]
I have updated the README to point to your project:

https://github.com/quackenbush/APC

**Comment by s-celles** [comment]
Thanks @quackenbush 
I didn't know [pexpect](https://pexpect.readthedocs.io/) previously.
So your project have been very useful for me and was a great tutorial to learn how to use this library.

**Comment by quackenbush** [comment]
You're welcome Sebastien.  Enjoy.
