### ISSUE TITLE
Make a package and have apc CLI available from any directory

### ISSUE THREAD

**Issue by scls19fr** [quackenbush/APC#4]
Hello,

Make a package (using `setup.py`) will be a nice improvement
apc.py should be available from any directory using

```python
entry_points={
        'console_scripts': [
            'apc=apc.cli_apc:main',
        ],
    },
```

Kind regards

**Comment by scls19fr** [comment]
Thanks to PR https://github.com/quackenbush/APC/pull/12 apc script can be called from any directory.

and thanks to https://github.com/quackenbush/APC/commit/8932f6c1ec79605a2bde7a2a9b7c7e2d17eb2ac1 command line is much shorter because we don't need to pass argument using CLI.

It can be easily installed using

```
pip install git+https://github.com/quackenbush/APC
```

Maybe we should consider publishing on PyPi ... but it's an additional work and we need to weight the pros and cons

**Comment by quackenbush** [comment]
Thanks for the work.  Let me investigate and get back to you at the end of the week.

**Comment by scls19fr** [comment]
All right!
That's not a problem for me. I'm currently using version from this branch
https://github.com/scls19fr/APC/tree/setup

**Comment by scls19fr** [comment]
Closed in my fork version (master branch) https://github.com/scls19fr/APC
