### ISSUE TITLE
License

### ISSUE THREAD

**Issue by scls19fr** [quackenbush/APC#7]
Hello,

I don't see any licence file. We should have one.

Kind regards

**Comment by scls19fr** [comment]
[lockfile.py](https://github.com/quackenbush/APC/commit/77541279d0b2ed3fc0ed9f11419c26d3da4954e3#diff-ec0a26be9bb7dc3e928ea5e0defff9b2) was taken from Twisted which was MIT licensed according https://github.com/pexip/os-twisted/blob/master/LICENSE

**Comment by quackenbush** [comment]
MIT license added
