### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by scls19fr** [quackenbush/APC#8]
Hello,

I haven't tested myself but I don't think this code can work with Windows

Pexpect seems to have only `pexpect.spawn` only on POSIX OS
https://stackoverflow.com/questions/1042778/can-i-use-expect-on-windows-without-installing-cygwin

I also haven't experienced this but "\r instead of \r\n could be an issue"
according https://github.com/jorgenhauge/APC/commit/5f555f4a68291306501a81abbc5a22f25b847e97
and https://stackoverflow.com/questions/10306410/python-telnet-automation-apc-pdu

Pinging @jorgenhauge

Kind regards

**Comment by scls19fr** [comment]
telnetlib https://docs.python.org/3.6/library/telnetlib.html could help

**Comment by quackenbush** [comment]
I don't have windows either.  If someone can validate \r\n I will commit that change.

**Comment by scls19fr** [comment]
Closed in favor of https://github.com/scls19fr/APC/issues/3
